### ISSUE TITLE
Issue with Journeymap

### ISSUE THREAD

**Issue by Zergmazter** [Ladysnake/Dissolution#102]
Whenever a waypoint is available/created and I die, I get this visual glitch. Its even the color of the waypoint. It happens in both survival and creative. Removing the waypoint seems to fix the visual glitch.

![2019-01-04_18 01 13](https://user-images.githubusercontent.com/17000034/50715458-55d31800-104b-11e9-84be-0e7a74ee88f1.png)

![2019-01-04_18 01 33](https://user-images.githubusercontent.com/17000034/50715467-62f00700-104b-11e9-8938-94a0e09e8fd5.png)

![2019-01-04_18 01 59](https://user-images.githubusercontent.com/17000034/50715475-697e7e80-104b-11e9-9b59-7f8ea5c0207a.png)

![2019-01-04_18 02 05](https://user-images.githubusercontent.com/17000034/50715478-6daa9c00-104b-11e9-9aa8-3d441dfebb9f.png)

![2019-01-04_18 02 20](https://user-images.githubusercontent.com/17000034/50715480-70a58c80-104b-11e9-8b3b-796f2678bdfd.png)

**Comment by Pyrofab** [comment]
So basically, the beacon effect is not rendered correctly, right ?

**Comment by Zergmazter** [comment]
It looks like I walked through it but I did not. I merely turned around in circles. It renders correctly at certain angle, but turning to a different angle does the glitch in the pictures, as if I walked through it. The worst part is this glitch follow you around blocking your view.

**Comment by Pyrofab** [comment]
Does this only happen in soul mode ? (does it stop when you are possessing something ?)

**Comment by Zergmazter** [comment]
It happens after I die and become soul. Let me see what happens when I possess someone.

**Comment by Pyrofab** [comment]
No need, I have uploaded a fix.

**Comment by Zergmazter** [comment]
Yep confirmed. That was fast thank you.
