### ISSUE TITLE
Suggestion: Config file variable to disable the undead's idle sounds

### ISSUE THREAD

**Issue by vitraiden** [Ladysnake/Dissolution#105]
Undead mobs make periodic 'idle' sounds (eg, zombies groan, skeletons make a sort of bone/xylophone sound).  This is good sound design as it alerts the player to the presence of danger.

It would be nice to be able to disable these sounds when made by a creature that hosts a Remnant player.  The frequency of the sounds gets annoying pretty quick.

**Comment by Pyrofab** [comment]
I kinda want to say "works as intended" there. The thing is, to make it work properly I would have to make it a server option, and it would indicate to other players that you are not a real zombie.

**Comment by vitraiden** [comment]
I'd personally be happy with a client-side option to stop my own host body from making noise constantly.  Would that be okay within your vision for the mod?

**Comment by Pyrofab** [comment]
I originally offered a server-side option as I thought it was not feasible on the client. However after digging some more, it may be possible. I will see what I can do.

**Comment by Pyrofab** [comment]
Nop, as I first thought, this is indeed not really feasible on the client (the mod cannot know what entity emitted the sound). So either server option or nothing.

**Comment by vitraiden** [comment]
That's unfortunate.  Well, do as you see fit regarding a server-side option.

Just my 2 cents, I think that Remnant players' movement patterns would betray them before a lack of sounds would.
