### ISSUE TITLE
Conflict with Wraith

### ISSUE THREAD

**Issue by EightBlade** [Ladysnake/Dissolution#123]
https://pastebin.com/BHyH5F0T

It appears the issue is with wraiths?

**Comment by Pyrofab** [comment]
Alright now that's unexpected... Could they maybe have registered wraths twice ?

**Comment by Pyrofab** [comment]
Alright, I think I know the issue. Do you have two different mods adding wraths by any chance ?

**Comment by EightBlade** [comment]
Probably, but I'm not sure which.

**Comment by Pyrofab** [comment]
I have uploaded a new version that should fix it. Let me know if there are further issues!
