### ISSUE TITLE
Retrocompatibility issue with old worlds

### ISSUE THREAD

**Issue by JuanoD** [Ladysnake/Dissolution#19]
I was testing the mod, and tried some stuff in a creative world.
I was looking to the ground and killed myself with a command, the game crashed and the logs relate the issue with waila (hwyla fork).

[latest.log](https://github.com/Pyrofab/Dissolution/files/1441432/latest.log)

Also, I have a question about the inventory. When I die and go to 0,0 to respawn, the corpse dissapear and all the inventory is gone. Is there a way to keep the corpse so I can go back to it and retrieve the items after I have respawned in 0,0? If it is, it can be locked so only corpse owner can retrieve the items?

**Comment by Pyrofab** [comment]
That crash is quite wierd. It looks like hwyla is triggering some unexpected condition... I'll need to test it myself but the fix should be in the next update.
Don't worry about that second part, next update will make it somewhat easier. Though currently you can use a config option to prevent corpses from despawning. About locking it, I could add that as a config option even though corpses are meant to be lootable.

**Comment by Pyrofab** [comment]
Well, I tested with latest version, seems like this issue is no more. Tell me if you still experience it.

**Comment by JuanoD** [comment]
Now corpses are not spawning, the message says
"Tried to add entity dissolution:player_corpse but it was marked as removed already"

**Comment by Pyrofab** [comment]
Version 0.5.2 adds a config to prevent anyone who's not either the corpse's owner or an OP from tempering with said corpse.

**Comment by Pyrofab** [comment]
Closing because the last updates have completely overlooked retrocompatibility anyway
