### ISSUE TITLE
Jei integration for crucible and mortar

### ISSUE THREAD

**Issue by lag42** [Ladysnake/Dissolution#20]
Jei integration for the crucible and mortar would be greatly appreciated

**Comment by Pyrofab** [comment]
That would be quite nice indeed, if a bit annoying as we need to make a gui just for it. It will come but in the meantime I'll update the wiki.

**Comment by lag42** [comment]
Can I at least get a basic explanation of how to get Mercury

**Comment by Pyrofab** [comment]
Of course !
First you harvest some magma blocks in the nether. Then you craft those into molten rocks, that you use on a water-filled crucible to get igneous rocks. You can then put an igneous rock in a mortar and crush it with a pestle (holding right click). Once you have powder, get the mortar back in your inventory and use it on a crucible. After that, you can separate the powder to get cinnabar powder. Finally, put the crucible on a fire to melt the cinnabar and get mercury (you'll need 8 igneous rocks worth of powder to get a bucket). To place the mercury, use the universal bucket (if enabled) or a jar.

**Comment by Pyrofab** [comment]
I just updated the wiki, would you mind telling me if there's enough information for now ?

**Comment by lag42** [comment]
Yep, seems fine
