### ISSUE TITLE
[Suggestion] More Soul Types

### ISSUE THREAD

**Issue by Darkmega18** [Ladysnake/Dissolution#32]
Pyrofab and Cobra, I would like to give you both some suggestions if possible on some soul types and some possible interactions for them. 

**Shattered Soul [moderate core]:** I'm making a modpack and in it's lore the player has a "Shattered Soul" meaning it can't easily tether them to a corporeal place due to a particularly devastating occurence that happened to them in a previous world. Where a vanilla soul would reincarnate in a bed with a body and all and keep going the shattered soul players are meant to keep getting kicked out of the overworld/corporeal dimensions and back to the "void" where it's urged to rest and heal. (in otherwords give up and just stay there and rest for a short eternity until they get their normal soul back in a later life)
So i was thinking a shattered soul could do just that. In a config a dimension ID could be added and every time the player is killed they could thrown to a dimension of the pack makers choosing and respawned there. With the possibility of it being a random location or a set location (spawn or a structure coded to spawn in said place located via coordinates) with maybe some set debuffs or less health etc.

**Forged Soul/Alchemist [Semi-hardcore]:** A soul type where the player can create fabricated bodies with some intricate crafting, either of a mechanical or biological nature. This allows them to possess the artificial bodies and continue on with the effects of the body in place. The bodies would cost experience and some physical resources and would act like the shells in the mod "Intangible" which the player could switch to and they have separate inventories... they could also be destroyed manually with a bit of time as they were just stationary player models that got your skin etc once possessed. In this mods case, being a death based soul switch the bodies could be pre outfitted with gear in case of emergency or placed in locations nearby so the dieing player can quickly respawn and zerg rush stuff.

**Deal with the Devil [Semi-hardcore]:** The player can find or create certain respawn shrines of a dark nature. Every time you die a dark spirit approaches you rapidly and asks you to pay up each time you want to revive. Which can be a physical item put into a special gui slot of some kind to be used after dead, or an xp cost or both. Upon paying up the spirit laughs and subtracts the cost and goes poof before allowing you to be teleported to any of your active dark shrines. If on the occasion you die and can't pay up, the spirit instead laughs and reaps you completely dead and you're game over. Rest in pepperinos.

**Horcrux [PvP or defense game oriented]:** A death type that respawns you like normal at special shrine locations that you select manually after a time delay, while respawning you can spectate but can't interact at all. You are tethered to a special item that must be hidden and kept existing at all times in special containers otherwise you're vulnerable to total destruction (game over). More of these items can be created but they cause more risk. As there are small debuffs for each horcrux you use up to a maximum allowed, and losing one will inflict massive debuffs on you and your respawn time and once the massive debuff goes away will leave stronger effects on you. Dieing without a horcrux placed down = dead.

_[this one might go a little far]_
**Wight/Wraith [Teamwork/co-op based]:** A player can set themselves as a wight or wraith. This means that they must possess themselves with another player or entity to exist. While outside of a body or entity they will slowly decay (a breathe bar of sorts) and take damage over time when exhausted. However a wraith can have it's own inventory in wraith form and within the entity it controls. Allowing it to do special maneuvers like jumping out of the entity's body to fight and help then re-enter etc. On death they're merely ejected back to wraith form and the body collapses.
Wraiths can also exist within the range of special beacons or altars that can be placed down allowing them to exist without slowly disappearing. While in wraith form they can do everything a spirit can do but aren't invulnerable, instead taking partial damage cause of their ethereal form but take bonus damage from magic.
When within spawn range of a wraith player other kinds of player body's will not be decayed and can be resurrected by the wraith allowing the player to resume without having to face their respective death penalties. Entities also once touched by the wraith will have this mechanic aswell but for less time allowing you to possibly jump between and keep pets and other follower type mobs alive. Rezzing costs some health and experience however. 
In the case of entities who are not players they will assume control on the entity until left by the wraith. If with another player the two can toggle control of the body but if not wanted the wraith can be ejected by the controlled one and stopped from possessing again in the case of abuse of control/teamwork/hijacking shenanigans.

Ok, done for now. I think I got carried away. >_>

**Comment by CobraDarkPoney** [comment]
Thanks for the suggestions! For now, we already have ideas for future SoS that actually quite resemble the "Forged soul" and the "Deal with the Devil" ideas you are proposing. So we'll concentrate on adding these before thinking about additional ones. But I really like your suggestions, and we might include them in future updates who knows.

On a personal note, I really appreciate your idea submission, as that shows you are interested in the mod, and motivates us to continue working for it. So thanks!

**Comment by CobraDarkPoney** [comment]
Oops

**Comment by Darkmega18** [comment]
Absolutely interested. So always glad to lend some inspiration.

I'd honestly really like the Shattered soul type if you could make that. Possibly as an alternative to vanilla so to override bed spawns for standard souls, but not quite full on soul like strong soul. As it would allow me to put it into my pack and make that the default style and possibly make ways for players to change their soul type so they can respawn in other ways later in the game. Since I want to limit respawn locations and emphasize using of teleportation monuments/recall stones from another mod for getting around to far off places and my only way to do that is to disable bed usage in all other dimensions with another mod that edits dimensions. But it makes the beds explode which is spooky and also quite surprising in a bad way to those who don't quite read my quest book or are just used to putting beds down and sleeping the night off like chickens... >_>

Also. do you think the mod would work fine with mods like hardcore revival/playerRevive where you can rez a player before they fully die? Since it plays a death message but keeps the player in the menu until they time out, give up or get picked up, so if this was in, I don't know if the two would collide and cause one or the other to no work properly if you were using a Soul other than vanilla.

**Comment by Pyrofab** [comment]
As a side note, a modpack maker could simulate all players being in the shattered soul state, as the config allows to specify a respawn dimension for all ghosts

**Comment by Darkmega18** [comment]
Ah, interesting. Just got no mobs spawning in my skyblock place to respawn the player into once they're kicked back. RIP. so unless you plan for it or get lucky in an unlucky way (cause mob spawns in a void dimension skyblock can get dicey) you get stuck in ghost mode. D:

**Comment by CobraDarkPoney** [comment]
What I think we can do, is in a future update add a soul state that makes you respawn in another dimension, without having to find a new body.

**Comment by Darkmega18** [comment]
which is pretty much the basics of shattered soul. so yay. :D

**Comment by MidnightvonCorgstein** [comment]
I like the wraith option personally.

**Comment by RiverLeviathan** [comment]
We pinned that issue to our mod dev channel on our Discord, in case we need these ideas in the future, since some are really interesting. Closing it for now as it's incompatible with the current direction of the mod.
