### ISSUE TITLE
Fire Damage Gives Strange Knockback

### ISSUE THREAD

**Issue by mario384** [Ladysnake/Dissolution#52]
When taking fire damage as an undead, the player is always knocked back in one specific direction.

**Comment by Pyrofab** [comment]
I have also noticed this issue but have not identified a reliable way to make it happen. If you could find out what triggers it, it could be very helpful.

**Comment by mario384** [comment]
Found it.  It happens if the mob you're currently controlling has been shot by a projectile.  The knockback takes the direction and amount of knockback you got from said attack.  Easiest way to see this is to aggro a skeleton and have it shoot you, then go get burned.

**Comment by Pyrofab** [comment]
Quite intriguing, thank you for the details
