### ISSUE TITLE
[BUG] Kicked from world when attacking while possessing undead.

### ISSUE THREAD

**Issue by Noxalas** [Ladysnake/Dissolution#56]
Hey there! Love the mod so far! :D 

Sadly, I'm getting kicked out of my world whenever I try attacking while possessing an undead mob.
Here's a log, hope it helps with finding the issue. 

- Noxalas

[latest.log](https://gist.github.com/Pyrofab/543ab9980b2c3ad75bb97830648124bc)

**Comment by Pyrofab** [comment]
What version of dissolution is this ? It is supposed to be fixed in Resurrection

**Comment by Noxalas** [comment]
I'm using the latest release. (Beta 0.1.1-resurrection)
It works completely fine by itself, so I would assume it's a compatibility issue.
