### ISSUE TITLE
Weird Crash with Creative mode, and standard zombie

### ISSUE THREAD

**Issue by MairuFrost** [Ladysnake/Dissolution#57]
Weird Crash with Creative mode, and standard zombie possestion, i was attacking a villager, and from the look of it, but i can not confirm, I became her and crashed? Also the world auto crashes on logging in now, and after 3 attempts i can't use the world anymore.

You can check out the crash log here:
[report](https://gist.github.com/MairuFrost/a6ee6785ec7fc262c04a1b6a037ce8a0)

**Comment by Pyrofab** [comment]
That's version 0.6.1, which was indeed very buggy. Please update to the new Beta.
