### ISSUE TITLE
[enhancement] a whitelist and blacklist for possession

### ISSUE THREAD

**Issue by lag42** [Ladysnake/Dissolution#59]
there are mobs from other mods that seem undead but aren't flagged undead, and mobs from other mobs from other mobs that don't seem undead but are flagged undead

a whitelist to allow mobs that aren't flagged undead to be possessed
and a blacklist to block mobs that are flagged undead from being possessed
these would be nice and allow for a lot more customizability

**Comment by Pyrofab** [comment]
I would rather have mod authors handle entity compatibility themselves so no whitelist for now, I may reconsider if a real need arises. Blacklist will be in by next update
