### ISSUE TITLE
[0.1.1-resurrection] Visual glitches in multiplayer

### ISSUE THREAD

**Issue by DaedalusGame** [Ladysnake/Dissolution#64]
Two visual bugs happen frequently in multiplayer:
- Remnants that are in spirit form will often not appear transparent or any different from normal
- Remnants possessing entities aren't marked invisible and appear riding on/inside of the entity they possess

I've also spotted a third one, where my player was transparent as if he should be in spirit form, but while I was human. Is this one intentional?

**Comment by Pyrofab** [comment]
Those bugs are theoretically fixed now, feel free to reopen if that's not the case
