### ISSUE TITLE
[0.1.1-resurrection] Self-harm

### ISSUE THREAD

**Issue by DaedalusGame** [Ladysnake/Dissolution#65]
As pointed out in #38, projectile weapons fired while possessing will hurt the possessed entity. This is still a problem in resurrection (despite apparently being ticked off as fixed(?))

Sometimes while moving, attacking can hurt and kill the possessed entity. I've had this happen on two occasions, one where I punched myself, and once I hit myself with a Smite 3 golden sword. Not very fun times were had by me that time.

Related to the second issue, when punching/mining grass or other blocks, possessed skeletons (not sure about others) will also frequently self-harm.

**Comment by Pyrofab** [comment]
The self harm when punching blocks is due to Swing Through Grass, the fix is already implemented just not released

**Comment by DaedalusGame** [comment]
ah i see

**Comment by Pyrofab** [comment]
I personally can't reproduce the self damage from projectiles, bows can be fired just fine. In fact, it should be the opposite, possessed entities cannot be hurt from your arrows at all. Maybe another mod is interfering ?

**Comment by DaedalusGame** [comment]
yeah, it's not arrows, i've tested a wand (with magic missile socketed) from ElectroBlob's wizardry but something tells me that it will be the same for all manner of projectile weapons

**Comment by Pyrofab** [comment]
Note: the Swing Through Grass fix works in singleplayer and not in multiplayer, for god knows what reason
