### ISSUE TITLE
[0.1.3] Remnant players are translucent, then eventually turn solid

### ISSUE THREAD

**Issue by DaedalusGame** [Ladysnake/Dissolution#69]
When joining a server, remnants appear translucent (even if they have a body), then eventually (I think it was after a dimension change), they turn solid again. Briefly while in another dimension i was completely invisible too. (Sidenote: I have the invisible if spirit config turned on)

EDIT: I just spawned in invisible (aside from my armor). Friend of mine who is also a remnant is fully solid.

**Comment by Pyrofab** [comment]
It's kind of hard for me to test those multiplayer issues, but so far I really can't reproduce that one. Does it look like there is a kind of trigger ?

**Comment by KomradeSpectre** [comment]
I've seen it happen mostly when two remnants join around the same time, and seems to fix when one dies and possesses a mob. The other remnant still retains translucency, but the one that died and possessed a mob becomes fully visible when converting back to their human state via flesh eating. Will do further tests.

**Comment by Pyrofab** [comment]
Happens when they join around the same time ? Thank you, I may have an idea.
