### ISSUE TITLE
There is an odd crash that occurs during loading when your mod and the following is in the same modpack...

### ISSUE THREAD

**Issue by Shade-Jonezy** [Ladysnake/Dissolution#70]
Iblis, an Upgradable Stats Mod.  The mod does create a zombie to hold your stuff, but can be switched off in the config, which I always turn off.  However, just as stated in the Title of This Issue, it causes the game to crash during loading with no details as to what caused the crash.  I even have Vanillafix Mod installed which also will give me the cause of crashes and it has no clue, but when I remove Iblis your mod no longer crashes my game.  Now I have sent Iblis Makers a message and posted an Issue on their GitHub Page.  All this is to let you in the crash and see if there is anything you can do on your end.

**Comment by Pyrofab** [comment]
Fixed in 0.1.5
