### ISSUE TITLE
Strange behavior when enter in a world

### ISSUE THREAD

**Issue by wenlfs** [Ladysnake/Dissolution#77]
I have this issue when I enter in the world that I left while was possessing a mob, it's due some mod interaction because I can't reproduce with Dissolution only but I can't find the culprit too. Happen that the player will behavior like in soul mode but possessing a mob, you can slide like a soul but you cant't jump and the two bodies are overlayed. Hope you understand what I'm trying to say and have better luck to find the solution.

![2018-10-25_10 51 04](https://user-images.githubusercontent.com/41978516/47519677-740ae380-d864-11e8-9b1f-a7e2339ca9a1.png)

Last log: [latest.log](https://github.com/Ladysnake/Dissolution/files/2516189/latest.log)

Thank you.

**Comment by Azvalk** [comment]
This happen to me too.
What are your mods ?
In this log I only see Quark that I have too. '-'

**Comment by wenlfs** [comment]
Mods list:
<details>
  <summary>Spoiler warning</summary>
  
  ItemPhysic - 1.4.0
OpenEye - OpenEye - 0.8
Advanced Fishing - 1.3.2
AlcatrazCore - 1.0.1
Antique Atlas - 4.4.9
AppleCore - 3.1.4
Tough As Nails - 3.1.0.129
Apple Juice Skin - 1.0.0.4
CraftTweaker2 - 4.1.11
MTLib - 3.0.5
Mod Tweaker - 4.0.15
Just Enough Items - 4.13.1.220
CTM - MC1.12.2-0.3.2.20
Mantle - 1.12-1.3.3.39
Better With Mods - 1.12-2.3.15
AppleSkin - 1.0.9
Quark - r1.5-130
AutoRegLib - 1.3-20
Auto Third Person - 1.2.0
Baubles - 1.5.2
Bauble Of Undying - 1.0.1
Bear With Me - 1.12.2-1.3.1
Better with Addons - 0.46
Shadowfacts' Forgelin - 1.7.4
Better Foliage - 2.2.0
Better Invisibility - 1.0
Better With Lib - ${version}
BiblioCraft - 2.4.5
Biomes O' Plenty - 7.0.1.2402
Bloodmoon - 1.5.3
Bookshelf - 2.3.567
Carry On - 1.11.1
Chop Down Updated - 1.1.3
Comforts - 1.3.1
Consecration - 0.0.12
Corail Pillar - Biomes O'Plenty Extension - 4.0.1
Corail Pillar - Quark Extension - 4.0.0
CoroUtil Library - 1.12.1-1.2.13
InGameConfigManager - 1.2.2
CreativeCore - 1.9.9
Customized Dungeon Loot - 1.0.2
Custom Nausea - 1.12.2-1.0
Diet Hopper - 1.1
Dynamic Lights - 1.4.9
Dynamic Surroundings - 3.4.9.17
Eerie Entities - 1.0.4
EnhancedSnowman - 1.0
Erebus - 1.0.23
Erosion - 2.2.1
Fancy Block Particles - 2.4.1
FastWorkbench - 1.5.3
Galaxite - 1.0.6
GeographiCraft - 0.8.7
Gravestone - 1.2.0
Gravestone mod - Extended - 1.3.1
Grue - 1.3.5
Overlord - 2.4.14
Guide-API - 1.12-2.1.7-62
Hardcore Darkness - 2.0
Horizontal Glass Panes - Release
iChunUtil - 7.1.4
Infused Ring Mod - 1.0.4
Inspirations - 1.12.2-0.2.3
JJ Meteor - 1.0.7
KleeSlabs - 5.4.11
Lighting Wand - 1.0.4
magma_monsters - 0.3.0
Minions - 2.0.3
MmmMmmMmmMmm - 1.12
MobAmputation - 7.0.0
PaintingSelectionGui - $version
Paintings++ - $version
No Tree Punching - 2.0.4
Ore Veins - 2.0.2
Potion Core - 1.6_for_1.12.2
Proportional Destruction Particles - 1.12.2-1.2.3
Prospectus - 1.8
Quality Tools - 1.0.6_for_1.12.2
Realistic Cobwebs Mod - 1.0.3
Redstone Paste - 1.7.5
Rough Mobs 2 - 2.0.0
Rustic - 1.0.12
Bone Torch Mod - @MAJOR@.@MINOR@.@REVIS@.@BUILD@
Serene Seasons - 1.2.6
Simple Corn - 2.4.1
Simple Tree Drops - 1.0.4
SkyLanterns - 1.12.1-1.0.1
Spartan Shields - 1.4.1
Spartan Weaponry - beta 1.2.3
Speed Based Fall Damage - 1.0.2
Campfire Spit - 1.12.2-1.3
Thrown Slime - 1.2.1
Tool Belt - 1.7.1
Tumbleweed - 1.11-0.4.5
The Twilight Forest - 3.8.689
Village Names - 2.0
Vulcanite - 1.3.11
Water Strainer - 3.2.0
Waystones - 4.0.67
Wearable Backpacks - 3.1.3
Localized Weather & Storms - 1.12.1-2.6.12
Wolf Armor and Storage - 2.2.3.6
WorldEdit - 6.1.8
WorldEdit CUI Forge Edition 2 - 2.1.2-mf-1.12.2-14.23.0.2487
XP Holder - 1.0.1
Zombie Players - 1.12.1-1.1.1
Zombie Awareness - 1.12.1-1.11.14
LadyLib - 2.3
Dissolution - 0.1.6
Midnight - 0.1.1
Survivalist - 2.1.6
The Betweenlands - 3.4.0
Corail Pillar - 4.2.1
   
</details>

To me it is happening even without Quark. Did you try more than one time? Because I experienced it too, the issue not happened on the first time that I enter.

**Comment by Azvalk** [comment]
oh.. it happened, without other mod..
I entered a skeleton.
I left the world, I came back, the bug was there.
I left, I came back, everything was fine, the bug was gone.
I left again, I came back, the bug was back.
I did this 5 time in a row, the bug persists.
So.. random or not.. i don't know..
