### ISSUE TITLE
Invisible monsters

### ISSUE THREAD

**Issue by Azvalk** [Ladysnake/Dissolution#79]
When you die killed by monsters, all monsters around you become invisible ( small area) , until you quit / re-enter world or until you died again.
These invisible monsters can attack..

Edit: hm.. don't happen when there is only Dissolution..
I will search what mod cause this among what I have ^^'

Edit 2 : CustomNPCs_1.12.224sep18snapshot '-' 
I will contact Noppes ^^'
He has already fixed some bug with Consecration that I reported =p

Edit 3: It's not CustomNpc xD
It happened again, without other mod, so it's a real bug of the mod. '-'
But it's random..

**Comment by Pyrofab** [comment]
Actually fixed in 0.3.0 !
