### ISSUE TITLE
Possessed Wither Skeletons Have Inappropiate Hitboxes

### ISSUE THREAD

**Issue by mario384** [Ladysnake/Dissolution#88]
They're able to walk into 2-block spaces, although they do suffocate.  However, this is not how collision usually works.  I also assume with larger mobs, it'd be the same as well.

**Comment by Pyrofab** [comment]
![code](https://cdn.discordapp.com/attachments/477596494837448704/528589455913648129/unknown.png)
I lowkey hoped no one would notice
