### ISSUE TITLE
Invincibility with absorption

### ISSUE THREAD

**Issue by mario384** [Ladysnake/Dissolution#89]
1. Any form of Absorption while possessed will make you invincible
2. Weakness affects undead mobs like a normal player by weakening them, instead of increasing their damage like other undead mobs
3. Certainly more nitpicky, but undead mobs keep the poison effect when given to them, despite their regular mob counterparts not being affected at all.

**Comment by Pyrofab** [comment]
2- The behaviour of weakness is definitely the vanilla one
3- Undead mobs do keep the poison effect, they just don't care
